name: Selenium Web Otomatisasi Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Chromium
        uses: browser-actions/setup-chrome@v1.6.1
        with:
          chrome-version: latest  # or use a different known version like '115.0.0.0'
          install-dependencies: false


      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Execute Tests
        run: ./gradlew apiTest

      - name: Download a Build Artifact (Optional)
        if: always()
        uses: actions/download-artifact@v3

      - name: Upload otomatisasi WEB
        uses: actions/upload-artifact@v4
        with:
          name: otomatisasi-report
          path: reports